#!/bin/sh
### BEGIN INIT INFO
# Provides:          sethostname_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: set custom hostname
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting sethostname_once"
    /sbin/sethostname.sh &&
    update-rc.d sethostname_once remove &&
    rm /etc/init.d/sethostname_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
